name: BizTech Grid
favicon: null
layout_spectrum: 0.2548157712444663
typography_spectrum: 0.8275878662243485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7053423335310072
  lightness: 0.0845257684122771
  saturation: 0.9746778255794197
  rhythmicContrast: 0.6592555278912187
purpose: []
